Repository epsagon/helm-charts, pull requests merged in 2021-02, with the labels that each got.

#2 Add validations with kubeval
  .github/kubeval.sh
  .gitignore
  charts/cluster-agent/ci/kubeval.yaml
Labels: size/S

#3 Validate helm charts
  charts/cluster-agent/Chart.yaml
  charts/cluster-agent/README.md
  charts/cluster-agent/README.md.gotmpl
  charts/cluster-agent/templates/NOTES.txt
  charts/cluster-agent/templates/_helpers.tpl
  charts/cluster-agent/templates/cluster-agent-deployment.yaml
  charts/cluster-agent/values.yaml
Labels: size/M

#4 Fixing k8s supported version
  charts/cluster-agent/README.md
Labels: size/XS

#5 Update template limits ep 5982
  charts/cluster-agent/templates/rbac.yaml
  charts/cluster-agent/values.yaml
Labels: size/S
